   $('#saveAsPicture').click(function() {
    var tmp_attr = $('#time-table').attr('class');
    $('#time-table').removeAttr('class');
    $('#time-table').css('width', '200%');
    $('#time-table').css('height', 'auto');
    $('#time-table td, th').css('padding', '5px');
    $('#time-table').css('font-size', '180%');
    html2canvas($('#time-table')).then(function(canvas) {
      var bgcanvas = document.createElement('canvas');
      bgcanvas.width = canvas.width;
      bgcanvas.height = canvas.height;
      var ctx = bgcanvas.getContext('2d');
      var gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
      gradient.addColorStop(0, 'rgba(255, 255, 255, 0.9)');
      gradient.addColorStop(1, 'rgba(221, 232, 255, 0.9)');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(canvas, 0, 0, canvas.width, canvas.height);
      var data = bgcanvas.toDataURL('image/png');
      data = data.replace('image/png', 'image/octet-stream');
      var downloadLink = document.createElement('a');
      downloadLink.href = data;
      downloadLink.download = '選課小幫手.png';
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
    });
    $('#time-table').removeAttr('height');
    $('#time-table').css('width', '100%');
    $('#time-table td, th').removeAttr('padding');
    $('#time-table').attr('class', tmp_attr);
    $('#time-table').css('font-size', '100%');
  });